### ISSUE TITLE
data

### ISSUE THREAD

**Issue by cjlortie** [cjlortie/Brome_on_the_range#1]
**D&D data**  
"Raw_Complete" is probably the one you're after.

**Comment by cjlortie** [comment]
Alex - are you able to try and wrangle in those next three datasets.  
a. Carrizo.csv in data folder  
b. DD_data.csv in data folder (the right one, thanks Jacob)  
c. then add a file and title it ERG.csv and wrangle it in too.

**Comment by afilazzola** [comment]
**Done**
Added ERG data
Expanded abbreviation list to include species from ERG dataset
Added Carrizo and ERG data in the same format as the shrub contrast loadings. Could all be combined
Filtered Mojave sites from shrub contrast because under Larrea and not Ephedra

**To do**
DD will need some more work because not species specific
Need expanded list of abbreviations for Carrizo dataset

**Comment by cjlortie** [comment]
OK.... I think we do these 4 only first.
contrast, carrizo, cuyama, and ERG  maybe... jacobs too

**Comment by cjlortie** [comment]
new issue in a second.
